### ISSUE TITLE
User consent and user notice

### ISSUE THREAD

**Issue by Denisthemalice** [ietf-wg-gnap/gnap-core-protocol#186] opened 2021-02-17 16:14 UTC
The end-user should be allowed to make choices.  It should be able accept to request an access token or not. This step is usually called "user consent". 

However, before making his choice, the end-user may wish to know for which reason(s) the choice is being proposed. This step is usually called "user notice".

This means that an optional pre-flight discovery scheme should be possible between a client and a RS, optionally followed by a "user notice" phase and a "user consent" phase. 

When the client has done that step once, then it may remember it and skip that step. In case of a subsequent failure e.g. because the access conditions to the RS have changed, the client may redo that step.

The choice may be between a set of logical conditions using OR and AND operators.

One possibility to implement such a scheme would be to define for a given RS three endpoints: a discovery endpoint, an access endpoint and a user consent endpoint.

See the issue about "Tentative proposal for a RS discovery mechanism".

**Comment by fimbault** [comment] 2021-03-02 13:15
Currently all that is managed by the UI during the interaction phase. By the way, the "user" in the consent phase is the RO. The "user" of the user notice could involve the RO (case when it is also the end-user), but more generally the "end-user" even if distinct from the RO (for instance, I'm a doctor and I need to ask my patient consent for x/y/z). 

There could be value in formalizing notice/consent as part of the interaction. The OR/AND operators could be a way to formalize also the choice, and doesn't preclude anyone from implementing whatever UI it wants. 

I think the discovery issue is different.

**Comment by Denisthemalice** [comment] 2021-03-02 17:02
In order to be able to consent to something, the choice must be clear for the end user and in the general case that choice can only be advertised by the RS, 

The presentation (choice of colors and of fonts) is up to the UI of the client, but the parameters of the choices are up to the RS. 
If would make sense to standardize the way the RS presents the parameters of these choices.

In addition, if the end-user wants to understand the reason for the choice, it should be able to get " a user notice" that explains the rational for each choice (in the preferred language of the end-user when possible).

**Comment by fimbault** [comment] 2021-03-02 17:05
I don't really think we can standardize the way this gets presented. There could be various design systems or ergonomic constraints, we probably don't want to get into that.

**Comment by Denisthemalice** [comment] 2021-03-03 16:16
Please reread my sentence above:

"The presentation (choice of colors and of fonts) is up to the UI of the client, but the parameters of the choices are up to the RS".

The presentation is out of the scope, but the parameters for the choices can be standardized.

With the GDPR, it is now possible to make a choice for the cookies. Unfortunately, these choices are different for every server. 
We should try to avoid the same situation. 

Privacy, with **User Consent** and **User Notice**, is important. It needs to be addressed in the document.

As soon as more than one AS is being considered, the **User Consent** and **User Notice** cannot be performed anymore at the AS level.

**Comment by fimbault** [comment] 2021-04-12 09:39
Same as #215 ?

**Comment by jricher** [comment] 2021-04-14 15:40
duplicate of #215 -- conversation moved there

**Closed by jricher** 2021-04-14 15:40 UTC
