### ISSUE TITLE
Terminology: Key

### ISSUE THREAD

**Issue by yaronf** [ietf-wg-gnap/gnap-core-protocol#8] opened 2020-11-01 13:42 UTC
Re: the "Elements" section.

Yaron: Can we call it something more specific, maybe "holder identity key"?

Justin: This isn’t just about a user’s key — this is primarily a key for the requesting client software, but it gets used in a number of ways. Keys can be bound to client instances and to access tokens, and they can be used to identify various parties in the system (including users). 

It was brought up in the design team meetings that we might not even need to define this term, since it’s understood in the wider security space, and so I’m happy to either take it out or expand it as required.

Yaron: I tend to agree we should remove it.

**Comment by fimbault** [comment] 2020-11-20 12:25
Closing as duplicate of #29

**Closed by fimbault** 2020-11-20 12:25 UTC
