### ISSUE TITLE
An overview is missing

### ISSUE THREAD

**Issue by Denisthemalice** [ietf-wg-gnap/gnap-core-protocol#235] opened 2021-04-02 14:55 UTC
On October 21, 2020 an email with the following subject :"Quick review of draft-ietf-gnap-core-protocol-00" 
has been sent and left unanswered. One of the questions was:

An overview is missing since the various features are only being discovered while reading the document.

It would be nice if the editors would be able to propose such an overview.

**Comment by jricher** [comment] 2021-04-02 15:29
Duplicate of #176

**Closed by jricher** 2021-04-02 15:29 UTC
