### ISSUE TITLE
Common points and main differences with OAuth ?

### ISSUE THREAD

**Issue by Denisthemalice** [ietf-wg-gnap/gnap-core-protocol#236] opened 2021-04-02 14:56 UTC
On October 21, 2020 an email with the following subject "Quick review of draft-ietf-gnap-core-protocol-00" 
has been sent and left unanswered. One of the questions was:

A key question that might interest a reader is the following: what are the common points and the main differences with OAuth ?

It would be nice if the editors would be able to propose a section or an Annex to answer to this question.

**Comment by jricher** [comment] 2021-04-02 15:28
Duplicate of #176

**Closed by jricher** 2021-04-02 15:28 UTC
