### ISSUE TITLE
The case of a RS trusting more that one AS

### ISSUE THREAD

**Issue by Denisthemalice** [ietf-wg-gnap/gnap-core-protocol#187] opened 2021-02-17 16:16 UTC
When a client has never contacted a RS before and in the case where the resource is protected by the means of an access token, 
it may wish to know which AS(s) are trusted by that RS and which kinds of privileges should be contained in an access token. 

As in the general case, an optional pre-flight discovery scheme should be possible between a client and a RS, optionally followed by a "user notice" phase and a "user consent" phase.

When the client has done that step once, then it may remember it and skip that step. In case of a subsequent failure e.g. because the access conditions to the RS have changed, the client may need to redo that step.

When the client has skipped that step, it should inform the AS that by a "user notice" phase and a "user consent" phase" needs to performed by the AS.

Here also, to implement such a scheme one possibility would be to define for a given AS three endpoints: a discovery endpoint, an access endpoint and a user consent endpoint.

See the issue about a "Tentative proposal for a RS discovery mechanism".

**Comment by fimbault** [comment] 2021-03-02 13:25
I think the possibility of multiple ASs can be independent on the rest of the assumptions here. We currently have nothing in the spec to cover that case, but it would be useful. We could have specialized ASs that you trust in different settings (e.g. one from the university, from the transportation system, etc.) but still want to combine services.

**Comment by Denisthemalice** [comment] 2021-03-02 17:02
There are two related points:
1. the fact hat we want to be able to support multiple ASs by a single RS, and
2. how to support multiple ASs by a single RS. See the issue #190 where I propose two possibilities: 

- advertising in advance or 
- a trial and error mechanism. 

Both approaches could co-exist.

**Comment by jricher** [comment] 2021-04-14 16:12
duplicate of #237

**Closed by jricher** 2021-04-14 16:12 UTC
