### ISSUE TITLE
Redundant "extending" sections

### ISSUE THREAD

**Issue by yaronf** [ietf-wg-gnap/gnap-core-protocol#395] opened 2022-02-20 22:41 UTC
3.3.5.  Extending Interaction Mode Responses is redundant with 2.5.4.  Extending Interaction Modes

(And I suspect there are more that are redundant between the request section and the response section.)

**Comment by jricher** [comment] 2022-02-21 13:15
Good note, but duplicate of #134

**Closed by jricher** 2022-02-21 13:15 UTC
