### ISSUE TITLE
Privacy considerations

### ISSUE THREAD

**Issue by Denisthemalice** [ietf-wg-gnap/gnap-core-protocol#234] opened 2021-04-01 15:24 UTC
Proposed additional text:

 Some end-users care about their privacy. When tokens are considered to be opaque for the clients, end-users are not supposed  
 to know which privileges (rights and/or attributes) have been placed inside an access token by an AS.

 ASs play a central role by delivering access tokens to clients. When an AS delivers rights to a client (and hence to an end-user), 
 it is in a position to know and to log which method(s) is/are likely to be performed by an end-user on some object(s) on a RS.

**Comment by jricher** [comment] 2021-04-01 15:37
Framing opaque access tokens as anti-privacy is incorrect and unhelpful.

**Comment by yaronf** [comment] 2021-04-01 16:53
I think this is a miscommunication. Would it be more acceptable if we said: When tokens are encrypted such that the client cannot inspect them...".

In other words, this is not about tokens being architecturally opaque (it should not be read by the client), rather it is about the token being physically opaque (really encrypted, cannot be read).

And to clarify: I think a fully transparent token can *still* be harmful to privacy. The question of token opacity is only weakly related to privacy IMO.

**Comment by Denisthemalice** [comment] 2021-04-01 17:13
**_@ yaronf_** : My text proposal has nothing to do with access token encryption. 

Since we are using HTTPs, an attacker external to the client will be unable to look at the content of an access token.


**_@jricher_** : I understood from a prior issue that, _for the time being_, access tokens should be considered as being opaque to clients. 
The text proposal is simply a consequence of such access token opacity.

.

**Comment by jricher** [comment] 2021-04-01 17:45
@yaronf the statement in this issue is about the tokens being architecturally opaque and placing a value judgement on that. I agree with you that transparent tokens can be harmful to privacy (and in fact are actually MORE harmful).

@Denisthemalice You are misunderstanding the prior issue and the discussion around that.

**Comment by fimbault** [comment] 2021-04-02 07:20
Closing as a duplicate of #133

**Closed by fimbault** 2021-04-02 07:20 UTC
