### ISSUE TITLE
Prior relationship or not between a RS and an AS

### ISSUE THREAD

**Issue by Denisthemalice** [ietf-wg-gnap/gnap-core-protocol#188] opened 2021-02-17 16:25 UTC
A prior relationship between a RS and a single AS is currently the current case considered in OAuth. 

Such a prior relationship allows to establish :

(1) on the RS side which AS is being trusted to issue capabilities on data objects protected by the RS (this is usually called a right) and
 
(2) on the AS side which RO is allowed to issue capabilities on data objects protected by the RS. 

A few thousands of AS may be expected while millions of RS may be expected. A RS may trust an AS for doing something without the need to establish a prior relationship between every AS and every RS.

This means that the current case of the issuance of capabilities by the AS (under the control of a RO), should be one case but that a second case should be supported: the issuance of end-user attributes (such as roles, group memberships, country of residence, town of residence, home address, country(ies) of citizenship, professional email or personal email, clearances, etc ...) by an AS. 

Note that the list of sub-id types defined in draft-ietf-secevent-subject-identifiers should be expanded to cover these cases.

The first case has some advantages in the context of an enterprise because the access management is controlled by the AS (in collaboration with the ROs), while the second case has major advantages in the context of both an enterprise and the Internet, because the access management is controlled only by the RS.

In the case of an enterprise environment, it should be possible either:

(1) to associate a RO only with a RS (for the verification of end-user attributes issued by some trusted ASs) or 

(2) to associate a RO with both an AS and a RS (for the issuance of capabilities by the AS, under the control of a RO and for their verification when they are presented to the RS). 

The second case (i.e. the issuance of end-user attributes) exhibits some interesting privacy characteristics: 

1.	The AS is unable to know which operation(s) will be performed by the Client on a RS.

2.	It is even possible in some cases to hide to an AS which RS(s) will be accessed by the Clients (see another issue with more details about: Hiding to an AS which RS(s) will be accessed by the Clients).

Under that second case, an Authorization Server alone would be unable to act as "Big Brother". 

As a conclusion, an access token should be able to contain:
     (1) capabilities on some data objects protected by a RS or/and 
     (2) end-user attributes.

**Comment by fimbault** [comment] 2021-03-02 13:36
I don't think it's the role of an AS to issue claims, but the AS could indeed provide some flexibility in managing assertions (as discussed in sub_ids, more on that at IETF110).

We had also some discussions on the mailing list related to the respective numbers of ASs vs RSs. In a SSI world, you could reach billions of ASs (potentially). Even if I agree that's not currently the case, and even if there's a difference between a wallet and an AS, we need to keep that in mind for the future. 

Then to be practical, what you suggest (making the distinction between capabilities and roles/groups) is discussed already in #203 and #192. Is there anything else to consider? (again we need to be able to identity practical changes that we could make to the text)

**Comment by Denisthemalice** [comment] 2021-03-02 17:03
The key point is that there should be a new section which clearly mentions early in the document the two cases:

(1) an access token able to contain capabilities on some data objects protected by a RS or/and
(2) an access token able to contain end-user attributes.

followed by a discussion of their advantages and drawbacks, in particular in terms of privacy and scalability.

At present, there is a lot of EXAMPLES following in sections **1.4.x** which are targeted to the very specific case where the end-user is also a RO. These examples should be moved into an annex. 

The general cases for the support of capabilities and attributes should be addressed within section 1.4. instead.

**Comment by fimbault** [comment] 2021-03-02 17:07
To me sections 1.4.3 and 1.4.4 correspond to the cases where RO != end-user. Please keep in mind that it's not always possible for the system to know in advance whether they're different.

**Comment by Denisthemalice** [comment] 2021-03-04 15:22
Sections 1.4.3 and 1.4.4 correspond to the case where a RS is trusting a single AS **whatever is the content of the access token** . 

They do not correspond to the general case where a RS can trust more than one AS, which is left unaddressed.

In addition, trusting an access token whatever its content would be is a too strong trust condition. 
The RO on the RS side should be able to say which content within the access token it will accept.

**Comment by fimbault** [comment] 2021-03-04 15:27
I think for clarity it would be much better to start from the current GNAP architecture (people don't have your target architecture or vocabulary in mind). 

That said, I agree we should aim at supporting multiple ASs.

**Comment by jricher** [comment] 2021-04-14 16:12
Duplicate of #237

**Closed by jricher** 2021-04-14 16:12 UTC
